version: '3.3'
services:
  data-science:
    image: chinkit/document-ml:v1.0.6
    ports:
      - "8888:8888"
    volumes:
      - ./code/:/home/jovyan/work/code/src
      - ./data/:/home/jovyan/work/code/data/