FROM jupyter/datascience-notebook

RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir \
    torch \
    scikit-learn \
    transformers[torch] \
    pytesseract

WORKDIR '/home/jovyan/work/code/'